//> using platform native
//> using dep com.armanbilge::epollcat::0.1.6
//> using nativeVersion 0.4.15
//> using toolkit typelevel::latest
//> using dep org.typelevel::mouse::1.2.1
//> using dep org.http4s::http4s-ember-server::0.23.23
//> using dep org.http4s::http4s-ember-client::0.23.23
//> using dep org.http4s::http4s-dsl::0.23.23
//> using dep org.typelevel::log4cats-noop::2.6.0
